### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by InFTord**
protected branches my beloved

### CODE REVIEW

**Comment by InFTord** [comment]
idc about table formatting btw :when:

**Comment by OoLunar** [comment]
:trollface:

**Comment by OoLunar** [comment]
You should fix the table formatting

**Comment by InFTord** [comment]
sdfsidjfosoejfiewjofwiejof fine

**Comment by InFTord** [comment]
hewwo lunar can you mewrge this puwull request 3>

**Review by Scordium — APPROVED** [review]
👍

**Comment by InFTord** [comment]
since lunar is lazy ass,

**Pull request merged**
